name: Update README

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual runs

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Latest Articles
        run: |
          echo "Fetching RSS feed from https://medium.com/feed/@CyberHackk"
          curl -s https://medium.com/feed/@CyberHackk -o raw_feed.xml
          echo "Printing the first 200 characters of the fetched feed"
          head -n 10 raw_feed.xml  # Print the first 200 characters to see the content
          
          # Parse the titles and update the README
          awk -F'<title>|</title>' '{print $2}' raw_feed.xml | head -n 5 > latest_articles.md

      - name: Update README
        run: |
          sed -i '/<!--LATEST_ARTICLES-->/r latest_articles.md' README.md
          rm latest_articles.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated latest articles"
          git push
